# {{RIPER-5:
#   Action: "Added"
#   Task_ID: "ec47c2ec-fcf4-4fba-9582-ee4c0dba3d77"
#   Timestamp: "2025-08-05T17:01:20+08:00"
#   Authoring_Role: "LD"
#   Principle_Applied: "DRY (Don't Repeat Yourself)"
#   Quality_Check: "代码质量工具配置完整，确保代码规范统一"
# }}
# {{START_MODIFICATIONS}}
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        files: ^python_src/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^python_src/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        files: ^python_src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        files: ^python_src/
        additional_dependencies: [types-all]
        args: [--python-version, "3.12"]
# {{END_MODIFICATIONS}}